
spring:
  application:
    name: e-commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: Initial version

    connect-retries: 2 
    schemas: ECOMMERCE
    table: flyway_schema_history

logging:
  level:
    root: INFO

